name: mlops-exaple-tensorflow-regression
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python model.py
          
          #report the result of model in a readme file for user friendly report
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
          
          # make it accessible for team members
          cml-send-comment report.md
